-- ============================================================================
-- Agency Command — Grid Plan Review, Part 2: Data Model
-- ============================================================================
-- Adds the tables behind the "Client Grid Plan Review" feature: the agency
-- builds a grid of upcoming posts, shares a private link with a client, and
-- the client reviews/comments/approves in-browser with no login.
--
-- PREREQUISITE: migration_grid_roles.sql must already be applied (this file
-- uses grid_can_manage()/grid_can_edit() from it).
-- HOW TO RUN: Supabase Dashboard → SQL Editor → paste this whole file → Run.
-- Safe to re-run.
--
-- SECURITY MODEL — read this before touching anything below:
--   These four tables get RLS enabled with policies ONLY for `authenticated`
--   org members (via my_org_id(), same pattern as every other table in this
--   app). There is deliberately NO anon/public policy on any of them. The
--   public, no-login client review page (/review/:share_token) must NEVER
--   talk to Supabase directly with the anon key — it goes entirely through
--   dedicated Edge Functions (review-load / review-update / review-reorder /
--   review-complete, added separately) which use the service-role key
--   server-side and validate the share_token themselves. That's what keeps
--   a client from ever being able to query another agency's data, no matter
--   what the browser sends.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. grid_plans — one per client review ("Acme Coffee — October grid")
-- ----------------------------------------------------------------------------
create table if not exists public.grid_plans (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations (id) on delete cascade,
  client_name text not null,
  -- Per-client accent color for the review page — profiles.color already
  -- established this "#rrggbb text column" convention elsewhere.
  accent_color text not null default '#7b2ff7',
  status text not null default 'draft'
    check (status in ('draft', 'shared', 'in_review', 'changes_requested', 'approved')),
  -- Long, random, unguessable — generated by the app when the plan is first
  -- shared (not by the DB), so a plan sitting in 'draft' has no token yet.
  -- Unique so a token can only ever resolve to exactly one plan (this is
  -- what the review-load Edge Function relies on for cross-plan isolation).
  share_token text unique,
  share_token_expires_at timestamptz,
  shared_at timestamptz,
  -- Set by the review-complete Edge Function when the client finishes;
  -- separate from `status = 'approved'` so "changes requested" still counts
  -- as the client having completed a review pass.
  client_completed_at timestamptz,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_grid_plans_org on public.grid_plans (org_id);
create index if not exists idx_grid_plans_share_token on public.grid_plans (share_token);

alter table public.grid_plans enable row level security;

drop policy if exists "grid_plans: read org" on public.grid_plans;
create policy "grid_plans: read org" on public.grid_plans
  for select using (org_id = public.my_org_id());

drop policy if exists "grid_plans: managers create" on public.grid_plans;
create policy "grid_plans: managers create" on public.grid_plans
  for insert with check (org_id = public.my_org_id() and public.grid_can_manage());

drop policy if exists "grid_plans: managers update" on public.grid_plans;
create policy "grid_plans: managers update" on public.grid_plans
  for update using (org_id = public.my_org_id() and public.grid_can_manage())
  with check (org_id = public.my_org_id() and public.grid_can_manage());

drop policy if exists "grid_plans: managers delete" on public.grid_plans;
create policy "grid_plans: managers delete" on public.grid_plans
  for delete using (org_id = public.my_org_id() and public.grid_can_manage());

drop trigger if exists trg_grid_plans_org on public.grid_plans;
create trigger trg_grid_plans_org
  before insert on public.grid_plans
  for each row execute function public.stamp_org_id();

drop trigger if exists trg_grid_plans_touch on public.grid_plans;
create trigger trg_grid_plans_touch
  before update on public.grid_plans
  for each row execute function public.touch_updated_at();

-- ----------------------------------------------------------------------------
-- 2. grid_posts — one per tile in the grid
-- ----------------------------------------------------------------------------
create table if not exists public.grid_posts (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references public.grid_plans (id) on delete cascade,
  org_id uuid not null references public.organizations (id) on delete cascade,
  position integer not null default 0,
  caption text not null default '',
  -- Deliberately a SEPARATE column from `caption`. A client once pasted an
  -- entire rewritten caption into what was meant to be a short note field,
  -- and it had to be migrated by hand — the review-page UI must keep these
  -- two fields visually distinct (see the review-page build step), and the
  -- data model keeps them structurally distinct here too.
  client_note text not null default '',
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'changes_requested')),
  post_date date,
  platform text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_grid_posts_plan on public.grid_posts (plan_id, position);
create index if not exists idx_grid_posts_org on public.grid_posts (org_id);

alter table public.grid_posts enable row level security;

drop policy if exists "grid_posts: read org" on public.grid_posts;
create policy "grid_posts: read org" on public.grid_posts
  for select using (org_id = public.my_org_id());

drop policy if exists "grid_posts: editors write" on public.grid_posts;
create policy "grid_posts: editors write" on public.grid_posts
  for insert with check (org_id = public.my_org_id() and public.grid_can_edit());

drop policy if exists "grid_posts: editors update" on public.grid_posts;
create policy "grid_posts: editors update" on public.grid_posts
  for update using (org_id = public.my_org_id() and public.grid_can_edit())
  with check (org_id = public.my_org_id() and public.grid_can_edit());

drop policy if exists "grid_posts: managers delete" on public.grid_posts;
create policy "grid_posts: managers delete" on public.grid_posts
  for delete using (org_id = public.my_org_id() and public.grid_can_manage());

drop trigger if exists trg_grid_posts_org on public.grid_posts;
create trigger trg_grid_posts_org
  before insert on public.grid_posts
  for each row execute function public.stamp_org_id();

drop trigger if exists trg_grid_posts_touch on public.grid_posts;
create trigger trg_grid_posts_touch
  before update on public.grid_posts
  for each row execute function public.touch_updated_at();

-- ----------------------------------------------------------------------------
-- 3. grid_post_media — image(s)/video for a post, stored in the private
--    `grid-media` bucket (created below). One post can have more than one
--    (e.g. a carousel), ordered by `position`.
-- ----------------------------------------------------------------------------
create table if not exists public.grid_post_media (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.grid_posts (id) on delete cascade,
  org_id uuid not null references public.organizations (id) on delete cascade,
  storage_path text not null,
  media_type text not null default 'image' check (media_type in ('image', 'video')),
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_grid_post_media_post on public.grid_post_media (post_id, position);
create index if not exists idx_grid_post_media_org on public.grid_post_media (org_id);

alter table public.grid_post_media enable row level security;

drop policy if exists "grid_post_media: read org" on public.grid_post_media;
create policy "grid_post_media: read org" on public.grid_post_media
  for select using (org_id = public.my_org_id());

drop policy if exists "grid_post_media: editors write" on public.grid_post_media;
create policy "grid_post_media: editors write" on public.grid_post_media
  for insert with check (org_id = public.my_org_id() and public.grid_can_edit());

drop policy if exists "grid_post_media: editors delete" on public.grid_post_media;
create policy "grid_post_media: editors delete" on public.grid_post_media
  for delete using (org_id = public.my_org_id() and public.grid_can_edit());

drop trigger if exists trg_grid_post_media_org on public.grid_post_media;
create trigger trg_grid_post_media_org
  before insert on public.grid_post_media
  for each row execute function public.stamp_org_id();

-- ----------------------------------------------------------------------------
-- 4. grid_activity — audit trail, mirrors the existing activity_log pattern.
--    Populated two ways:
--      a) automatically, by the trigger below, whenever a grid_posts row's
--         content actually changes (agency edits AND client edits routed
--         through the service-role Edge Functions both fire it — triggers
--         run regardless of RLS/service-role bypass);
--      b) manually, by app/Edge Function code, for events that aren't a
--         plain row UPDATE (e.g. "plan shared", "client approved", and
--         keep-both conflict resolutions, which log the discarded version
--         into before_value).
-- ----------------------------------------------------------------------------
create table if not exists public.grid_activity (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations (id) on delete cascade,
  plan_id uuid not null references public.grid_plans (id) on delete cascade,
  post_id uuid references public.grid_posts (id) on delete set null,
  -- 'agency' = a signed-in team member did this; 'client' = it came through
  -- a review-* Edge Function call authenticated only by share_token.
  actor_type text not null check (actor_type in ('agency', 'client')),
  actor_id uuid references public.profiles (id) on delete set null,
  action text not null,
  before_value jsonb,
  after_value jsonb,
  message text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_grid_activity_plan on public.grid_activity (plan_id, created_at desc);
create index if not exists idx_grid_activity_org on public.grid_activity (org_id);

alter table public.grid_activity enable row level security;

drop policy if exists "grid_activity: read org" on public.grid_activity;
create policy "grid_activity: read org" on public.grid_activity
  for select using (org_id = public.my_org_id());

-- Agency-side manual inserts (e.g. logging "plan shared") — anyone who can
-- edit the plan's content can also write an activity row. The Edge
-- Functions use the service-role key, which bypasses RLS entirely, so
-- client-originated inserts don't need (and don't get) a policy here.
drop policy if exists "grid_activity: editors insert" on public.grid_activity;
create policy "grid_activity: editors insert" on public.grid_activity
  for insert with check (org_id = public.my_org_id() and public.grid_can_edit());

-- Auto-log real content changes on grid_posts. Security definer so it can
-- write to grid_activity regardless of who/what triggered the update
-- (signed-in teammate OR the service-role Edge Function on the client's
-- behalf, which has no auth.uid()).
create or replace function public.log_grid_post_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  changed_fields jsonb := '{}'::jsonb;
  before_fields jsonb := '{}'::jsonb;
  who uuid := auth.uid();
begin
  if new.caption is distinct from old.caption then
    before_fields := before_fields || jsonb_build_object('caption', old.caption);
    changed_fields := changed_fields || jsonb_build_object('caption', new.caption);
  end if;
  if new.client_note is distinct from old.client_note then
    before_fields := before_fields || jsonb_build_object('client_note', old.client_note);
    changed_fields := changed_fields || jsonb_build_object('client_note', new.client_note);
  end if;
  if new.status is distinct from old.status then
    before_fields := before_fields || jsonb_build_object('status', old.status);
    changed_fields := changed_fields || jsonb_build_object('status', new.status);
  end if;
  if new.position is distinct from old.position then
    before_fields := before_fields || jsonb_build_object('position', old.position);
    changed_fields := changed_fields || jsonb_build_object('position', new.position);
  end if;

  if changed_fields = '{}'::jsonb then
    return new;
  end if;

  insert into public.grid_activity (org_id, plan_id, post_id, actor_type, actor_id, action, before_value, after_value, message)
  values (
    new.org_id,
    new.plan_id,
    new.id,
    case when who is null then 'client' else 'agency' end,
    who,
    'post_updated',
    before_fields,
    changed_fields,
    'Post updated'
  );

  return new;
end;
$$;

drop trigger if exists trg_log_grid_post_changes on public.grid_posts;
create trigger trg_log_grid_post_changes
  after update on public.grid_posts
  for each row execute function public.log_grid_post_changes();

-- ----------------------------------------------------------------------------
-- 5. Storage: private `grid-media` bucket
-- ----------------------------------------------------------------------------
-- public = false, unlike the existing `avatars` bucket — media is only ever
-- served via signed URLs (agency side: normal authenticated storage RLS
-- below; client side: a short-lived signed URL minted by the review-load
-- Edge Function using the service-role key). No policy here ever allows an
-- anonymous/public read.
insert into storage.buckets (id, name, public)
values ('grid-media', 'grid-media', false)
on conflict (id) do nothing;

-- Path convention: "<org_id>/<plan_id>/<filename>" — mirrors the avatars
-- bucket's "<user_id>/filename" folder-prefix pattern. Only signed-in
-- members of that org can read/write inside their own org's folder.
drop policy if exists "grid-media: org read" on storage.objects;
create policy "grid-media: org read" on storage.objects
  for select using (
    bucket_id = 'grid-media'
    and (storage.foldername(name))[1] = public.my_org_id()::text
  );

drop policy if exists "grid-media: editors upload" on storage.objects;
create policy "grid-media: editors upload" on storage.objects
  for insert with check (
    bucket_id = 'grid-media'
    and (storage.foldername(name))[1] = public.my_org_id()::text
    and public.grid_can_edit()
  );

drop policy if exists "grid-media: editors delete" on storage.objects;
create policy "grid-media: editors delete" on storage.objects
  for delete using (
    bucket_id = 'grid-media'
    and (storage.foldername(name))[1] = public.my_org_id()::text
    and public.grid_can_edit()
  );

-- ----------------------------------------------------------------------------
-- 6. Realtime: add the two live-editing tables to the same publication
--    every other realtime table in this app already uses.
-- ----------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'grid_posts'
  ) then
    alter publication supabase_realtime add table public.grid_posts;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'grid_plans'
  ) then
    alter publication supabase_realtime add table public.grid_plans;
  end if;
end $$;

-- ============================================================================
-- DONE. This alone changes nothing visible yet in the app — no view calls
-- these tables. Next slice: the Team screen's role picker, then the agency
-- plan builder UI.
-- ============================================================================
